
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FavoriteGame` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/wasm-compiler-edge"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model FavoriteGame
 * 
 */
export type FavoriteGameModel = runtime.Types.Result.DefaultSelection<Prisma.$FavoriteGamePayload>

export type AggregateFavoriteGame = {
  _count: FavoriteGameCountAggregateOutputType | null
  _min: FavoriteGameMinAggregateOutputType | null
  _max: FavoriteGameMaxAggregateOutputType | null
}

export type FavoriteGameMinAggregateOutputType = {
  id: string | null
  userId: string | null
  gameKey: string | null
  createdAt: Date | null
}

export type FavoriteGameMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  gameKey: string | null
  createdAt: Date | null
}

export type FavoriteGameCountAggregateOutputType = {
  id: number
  userId: number
  gameKey: number
  createdAt: number
  _all: number
}


export type FavoriteGameMinAggregateInputType = {
  id?: true
  userId?: true
  gameKey?: true
  createdAt?: true
}

export type FavoriteGameMaxAggregateInputType = {
  id?: true
  userId?: true
  gameKey?: true
  createdAt?: true
}

export type FavoriteGameCountAggregateInputType = {
  id?: true
  userId?: true
  gameKey?: true
  createdAt?: true
  _all?: true
}

export type FavoriteGameAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FavoriteGame to aggregate.
   */
  where?: Prisma.FavoriteGameWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FavoriteGames to fetch.
   */
  orderBy?: Prisma.FavoriteGameOrderByWithRelationInput | Prisma.FavoriteGameOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FavoriteGameWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FavoriteGames from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FavoriteGames.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FavoriteGames
  **/
  _count?: true | FavoriteGameCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FavoriteGameMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FavoriteGameMaxAggregateInputType
}

export type GetFavoriteGameAggregateType<T extends FavoriteGameAggregateArgs> = {
      [P in keyof T & keyof AggregateFavoriteGame]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFavoriteGame[P]>
    : Prisma.GetScalarType<T[P], AggregateFavoriteGame[P]>
}




export type FavoriteGameGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FavoriteGameWhereInput
  orderBy?: Prisma.FavoriteGameOrderByWithAggregationInput | Prisma.FavoriteGameOrderByWithAggregationInput[]
  by: Prisma.FavoriteGameScalarFieldEnum[] | Prisma.FavoriteGameScalarFieldEnum
  having?: Prisma.FavoriteGameScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FavoriteGameCountAggregateInputType | true
  _min?: FavoriteGameMinAggregateInputType
  _max?: FavoriteGameMaxAggregateInputType
}

export type FavoriteGameGroupByOutputType = {
  id: string
  userId: string
  gameKey: string
  createdAt: Date
  _count: FavoriteGameCountAggregateOutputType | null
  _min: FavoriteGameMinAggregateOutputType | null
  _max: FavoriteGameMaxAggregateOutputType | null
}

export type GetFavoriteGameGroupByPayload<T extends FavoriteGameGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FavoriteGameGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FavoriteGameGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FavoriteGameGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FavoriteGameGroupByOutputType[P]>
      }
    >
  >



export type FavoriteGameWhereInput = {
  AND?: Prisma.FavoriteGameWhereInput | Prisma.FavoriteGameWhereInput[]
  OR?: Prisma.FavoriteGameWhereInput[]
  NOT?: Prisma.FavoriteGameWhereInput | Prisma.FavoriteGameWhereInput[]
  id?: Prisma.StringFilter<"FavoriteGame"> | string
  userId?: Prisma.StringFilter<"FavoriteGame"> | string
  gameKey?: Prisma.StringFilter<"FavoriteGame"> | string
  createdAt?: Prisma.DateTimeFilter<"FavoriteGame"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type FavoriteGameOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  gameKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type FavoriteGameWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId_gameKey?: Prisma.FavoriteGameUserIdGameKeyCompoundUniqueInput
  AND?: Prisma.FavoriteGameWhereInput | Prisma.FavoriteGameWhereInput[]
  OR?: Prisma.FavoriteGameWhereInput[]
  NOT?: Prisma.FavoriteGameWhereInput | Prisma.FavoriteGameWhereInput[]
  userId?: Prisma.StringFilter<"FavoriteGame"> | string
  gameKey?: Prisma.StringFilter<"FavoriteGame"> | string
  createdAt?: Prisma.DateTimeFilter<"FavoriteGame"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "userId_gameKey">

export type FavoriteGameOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  gameKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.FavoriteGameCountOrderByAggregateInput
  _max?: Prisma.FavoriteGameMaxOrderByAggregateInput
  _min?: Prisma.FavoriteGameMinOrderByAggregateInput
}

export type FavoriteGameScalarWhereWithAggregatesInput = {
  AND?: Prisma.FavoriteGameScalarWhereWithAggregatesInput | Prisma.FavoriteGameScalarWhereWithAggregatesInput[]
  OR?: Prisma.FavoriteGameScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FavoriteGameScalarWhereWithAggregatesInput | Prisma.FavoriteGameScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FavoriteGame"> | string
  userId?: Prisma.StringWithAggregatesFilter<"FavoriteGame"> | string
  gameKey?: Prisma.StringWithAggregatesFilter<"FavoriteGame"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"FavoriteGame"> | Date | string
}

export type FavoriteGameCreateInput = {
  id?: string
  gameKey: string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutFavoriteGamesInput
}

export type FavoriteGameUncheckedCreateInput = {
  id?: string
  userId: string
  gameKey: string
  createdAt?: Date | string
}

export type FavoriteGameUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gameKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutFavoriteGamesNestedInput
}

export type FavoriteGameUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  gameKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FavoriteGameCreateManyInput = {
  id?: string
  userId: string
  gameKey: string
  createdAt?: Date | string
}

export type FavoriteGameUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gameKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FavoriteGameUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  gameKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FavoriteGameListRelationFilter = {
  every?: Prisma.FavoriteGameWhereInput
  some?: Prisma.FavoriteGameWhereInput
  none?: Prisma.FavoriteGameWhereInput
}

export type FavoriteGameOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FavoriteGameUserIdGameKeyCompoundUniqueInput = {
  userId: string
  gameKey: string
}

export type FavoriteGameCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  gameKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type FavoriteGameMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  gameKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type FavoriteGameMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  gameKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type FavoriteGameCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.FavoriteGameCreateWithoutUserInput, Prisma.FavoriteGameUncheckedCreateWithoutUserInput> | Prisma.FavoriteGameCreateWithoutUserInput[] | Prisma.FavoriteGameUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FavoriteGameCreateOrConnectWithoutUserInput | Prisma.FavoriteGameCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.FavoriteGameCreateManyUserInputEnvelope
  connect?: Prisma.FavoriteGameWhereUniqueInput | Prisma.FavoriteGameWhereUniqueInput[]
}

export type FavoriteGameUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.FavoriteGameCreateWithoutUserInput, Prisma.FavoriteGameUncheckedCreateWithoutUserInput> | Prisma.FavoriteGameCreateWithoutUserInput[] | Prisma.FavoriteGameUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FavoriteGameCreateOrConnectWithoutUserInput | Prisma.FavoriteGameCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.FavoriteGameCreateManyUserInputEnvelope
  connect?: Prisma.FavoriteGameWhereUniqueInput | Prisma.FavoriteGameWhereUniqueInput[]
}

export type FavoriteGameUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.FavoriteGameCreateWithoutUserInput, Prisma.FavoriteGameUncheckedCreateWithoutUserInput> | Prisma.FavoriteGameCreateWithoutUserInput[] | Prisma.FavoriteGameUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FavoriteGameCreateOrConnectWithoutUserInput | Prisma.FavoriteGameCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.FavoriteGameUpsertWithWhereUniqueWithoutUserInput | Prisma.FavoriteGameUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.FavoriteGameCreateManyUserInputEnvelope
  set?: Prisma.FavoriteGameWhereUniqueInput | Prisma.FavoriteGameWhereUniqueInput[]
  disconnect?: Prisma.FavoriteGameWhereUniqueInput | Prisma.FavoriteGameWhereUniqueInput[]
  delete?: Prisma.FavoriteGameWhereUniqueInput | Prisma.FavoriteGameWhereUniqueInput[]
  connect?: Prisma.FavoriteGameWhereUniqueInput | Prisma.FavoriteGameWhereUniqueInput[]
  update?: Prisma.FavoriteGameUpdateWithWhereUniqueWithoutUserInput | Prisma.FavoriteGameUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.FavoriteGameUpdateManyWithWhereWithoutUserInput | Prisma.FavoriteGameUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.FavoriteGameScalarWhereInput | Prisma.FavoriteGameScalarWhereInput[]
}

export type FavoriteGameUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.FavoriteGameCreateWithoutUserInput, Prisma.FavoriteGameUncheckedCreateWithoutUserInput> | Prisma.FavoriteGameCreateWithoutUserInput[] | Prisma.FavoriteGameUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FavoriteGameCreateOrConnectWithoutUserInput | Prisma.FavoriteGameCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.FavoriteGameUpsertWithWhereUniqueWithoutUserInput | Prisma.FavoriteGameUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.FavoriteGameCreateManyUserInputEnvelope
  set?: Prisma.FavoriteGameWhereUniqueInput | Prisma.FavoriteGameWhereUniqueInput[]
  disconnect?: Prisma.FavoriteGameWhereUniqueInput | Prisma.FavoriteGameWhereUniqueInput[]
  delete?: Prisma.FavoriteGameWhereUniqueInput | Prisma.FavoriteGameWhereUniqueInput[]
  connect?: Prisma.FavoriteGameWhereUniqueInput | Prisma.FavoriteGameWhereUniqueInput[]
  update?: Prisma.FavoriteGameUpdateWithWhereUniqueWithoutUserInput | Prisma.FavoriteGameUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.FavoriteGameUpdateManyWithWhereWithoutUserInput | Prisma.FavoriteGameUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.FavoriteGameScalarWhereInput | Prisma.FavoriteGameScalarWhereInput[]
}

export type FavoriteGameCreateWithoutUserInput = {
  id?: string
  gameKey: string
  createdAt?: Date | string
}

export type FavoriteGameUncheckedCreateWithoutUserInput = {
  id?: string
  gameKey: string
  createdAt?: Date | string
}

export type FavoriteGameCreateOrConnectWithoutUserInput = {
  where: Prisma.FavoriteGameWhereUniqueInput
  create: Prisma.XOR<Prisma.FavoriteGameCreateWithoutUserInput, Prisma.FavoriteGameUncheckedCreateWithoutUserInput>
}

export type FavoriteGameCreateManyUserInputEnvelope = {
  data: Prisma.FavoriteGameCreateManyUserInput | Prisma.FavoriteGameCreateManyUserInput[]
}

export type FavoriteGameUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.FavoriteGameWhereUniqueInput
  update: Prisma.XOR<Prisma.FavoriteGameUpdateWithoutUserInput, Prisma.FavoriteGameUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.FavoriteGameCreateWithoutUserInput, Prisma.FavoriteGameUncheckedCreateWithoutUserInput>
}

export type FavoriteGameUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.FavoriteGameWhereUniqueInput
  data: Prisma.XOR<Prisma.FavoriteGameUpdateWithoutUserInput, Prisma.FavoriteGameUncheckedUpdateWithoutUserInput>
}

export type FavoriteGameUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.FavoriteGameScalarWhereInput
  data: Prisma.XOR<Prisma.FavoriteGameUpdateManyMutationInput, Prisma.FavoriteGameUncheckedUpdateManyWithoutUserInput>
}

export type FavoriteGameScalarWhereInput = {
  AND?: Prisma.FavoriteGameScalarWhereInput | Prisma.FavoriteGameScalarWhereInput[]
  OR?: Prisma.FavoriteGameScalarWhereInput[]
  NOT?: Prisma.FavoriteGameScalarWhereInput | Prisma.FavoriteGameScalarWhereInput[]
  id?: Prisma.StringFilter<"FavoriteGame"> | string
  userId?: Prisma.StringFilter<"FavoriteGame"> | string
  gameKey?: Prisma.StringFilter<"FavoriteGame"> | string
  createdAt?: Prisma.DateTimeFilter<"FavoriteGame"> | Date | string
}

export type FavoriteGameCreateManyUserInput = {
  id?: string
  gameKey: string
  createdAt?: Date | string
}

export type FavoriteGameUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gameKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FavoriteGameUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gameKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FavoriteGameUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gameKey?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type FavoriteGameSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  gameKey?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["favoriteGame"]>

export type FavoriteGameSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  gameKey?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["favoriteGame"]>

export type FavoriteGameSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  gameKey?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["favoriteGame"]>

export type FavoriteGameSelectScalar = {
  id?: boolean
  userId?: boolean
  gameKey?: boolean
  createdAt?: boolean
}

export type FavoriteGameOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "gameKey" | "createdAt", ExtArgs["result"]["favoriteGame"]>
export type FavoriteGameInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type FavoriteGameIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type FavoriteGameIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $FavoriteGamePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FavoriteGame"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    gameKey: string
    createdAt: Date
  }, ExtArgs["result"]["favoriteGame"]>
  composites: {}
}

export type FavoriteGameGetPayload<S extends boolean | null | undefined | FavoriteGameDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FavoriteGamePayload, S>

export type FavoriteGameCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FavoriteGameFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FavoriteGameCountAggregateInputType | true
  }

export interface FavoriteGameDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FavoriteGame'], meta: { name: 'FavoriteGame' } }
  /**
   * Find zero or one FavoriteGame that matches the filter.
   * @param {FavoriteGameFindUniqueArgs} args - Arguments to find a FavoriteGame
   * @example
   * // Get one FavoriteGame
   * const favoriteGame = await prisma.favoriteGame.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FavoriteGameFindUniqueArgs>(args: Prisma.SelectSubset<T, FavoriteGameFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FavoriteGameClient<runtime.Types.Result.GetResult<Prisma.$FavoriteGamePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FavoriteGame that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FavoriteGameFindUniqueOrThrowArgs} args - Arguments to find a FavoriteGame
   * @example
   * // Get one FavoriteGame
   * const favoriteGame = await prisma.favoriteGame.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FavoriteGameFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FavoriteGameFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FavoriteGameClient<runtime.Types.Result.GetResult<Prisma.$FavoriteGamePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FavoriteGame that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FavoriteGameFindFirstArgs} args - Arguments to find a FavoriteGame
   * @example
   * // Get one FavoriteGame
   * const favoriteGame = await prisma.favoriteGame.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FavoriteGameFindFirstArgs>(args?: Prisma.SelectSubset<T, FavoriteGameFindFirstArgs<ExtArgs>>): Prisma.Prisma__FavoriteGameClient<runtime.Types.Result.GetResult<Prisma.$FavoriteGamePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FavoriteGame that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FavoriteGameFindFirstOrThrowArgs} args - Arguments to find a FavoriteGame
   * @example
   * // Get one FavoriteGame
   * const favoriteGame = await prisma.favoriteGame.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FavoriteGameFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FavoriteGameFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FavoriteGameClient<runtime.Types.Result.GetResult<Prisma.$FavoriteGamePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FavoriteGames that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FavoriteGameFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FavoriteGames
   * const favoriteGames = await prisma.favoriteGame.findMany()
   * 
   * // Get first 10 FavoriteGames
   * const favoriteGames = await prisma.favoriteGame.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const favoriteGameWithIdOnly = await prisma.favoriteGame.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FavoriteGameFindManyArgs>(args?: Prisma.SelectSubset<T, FavoriteGameFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FavoriteGamePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FavoriteGame.
   * @param {FavoriteGameCreateArgs} args - Arguments to create a FavoriteGame.
   * @example
   * // Create one FavoriteGame
   * const FavoriteGame = await prisma.favoriteGame.create({
   *   data: {
   *     // ... data to create a FavoriteGame
   *   }
   * })
   * 
   */
  create<T extends FavoriteGameCreateArgs>(args: Prisma.SelectSubset<T, FavoriteGameCreateArgs<ExtArgs>>): Prisma.Prisma__FavoriteGameClient<runtime.Types.Result.GetResult<Prisma.$FavoriteGamePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FavoriteGames.
   * @param {FavoriteGameCreateManyArgs} args - Arguments to create many FavoriteGames.
   * @example
   * // Create many FavoriteGames
   * const favoriteGame = await prisma.favoriteGame.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FavoriteGameCreateManyArgs>(args?: Prisma.SelectSubset<T, FavoriteGameCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FavoriteGames and returns the data saved in the database.
   * @param {FavoriteGameCreateManyAndReturnArgs} args - Arguments to create many FavoriteGames.
   * @example
   * // Create many FavoriteGames
   * const favoriteGame = await prisma.favoriteGame.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FavoriteGames and only return the `id`
   * const favoriteGameWithIdOnly = await prisma.favoriteGame.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FavoriteGameCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FavoriteGameCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FavoriteGamePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FavoriteGame.
   * @param {FavoriteGameDeleteArgs} args - Arguments to delete one FavoriteGame.
   * @example
   * // Delete one FavoriteGame
   * const FavoriteGame = await prisma.favoriteGame.delete({
   *   where: {
   *     // ... filter to delete one FavoriteGame
   *   }
   * })
   * 
   */
  delete<T extends FavoriteGameDeleteArgs>(args: Prisma.SelectSubset<T, FavoriteGameDeleteArgs<ExtArgs>>): Prisma.Prisma__FavoriteGameClient<runtime.Types.Result.GetResult<Prisma.$FavoriteGamePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FavoriteGame.
   * @param {FavoriteGameUpdateArgs} args - Arguments to update one FavoriteGame.
   * @example
   * // Update one FavoriteGame
   * const favoriteGame = await prisma.favoriteGame.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FavoriteGameUpdateArgs>(args: Prisma.SelectSubset<T, FavoriteGameUpdateArgs<ExtArgs>>): Prisma.Prisma__FavoriteGameClient<runtime.Types.Result.GetResult<Prisma.$FavoriteGamePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FavoriteGames.
   * @param {FavoriteGameDeleteManyArgs} args - Arguments to filter FavoriteGames to delete.
   * @example
   * // Delete a few FavoriteGames
   * const { count } = await prisma.favoriteGame.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FavoriteGameDeleteManyArgs>(args?: Prisma.SelectSubset<T, FavoriteGameDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FavoriteGames.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FavoriteGameUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FavoriteGames
   * const favoriteGame = await prisma.favoriteGame.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FavoriteGameUpdateManyArgs>(args: Prisma.SelectSubset<T, FavoriteGameUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FavoriteGames and returns the data updated in the database.
   * @param {FavoriteGameUpdateManyAndReturnArgs} args - Arguments to update many FavoriteGames.
   * @example
   * // Update many FavoriteGames
   * const favoriteGame = await prisma.favoriteGame.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FavoriteGames and only return the `id`
   * const favoriteGameWithIdOnly = await prisma.favoriteGame.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FavoriteGameUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FavoriteGameUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FavoriteGamePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FavoriteGame.
   * @param {FavoriteGameUpsertArgs} args - Arguments to update or create a FavoriteGame.
   * @example
   * // Update or create a FavoriteGame
   * const favoriteGame = await prisma.favoriteGame.upsert({
   *   create: {
   *     // ... data to create a FavoriteGame
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FavoriteGame we want to update
   *   }
   * })
   */
  upsert<T extends FavoriteGameUpsertArgs>(args: Prisma.SelectSubset<T, FavoriteGameUpsertArgs<ExtArgs>>): Prisma.Prisma__FavoriteGameClient<runtime.Types.Result.GetResult<Prisma.$FavoriteGamePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FavoriteGames.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FavoriteGameCountArgs} args - Arguments to filter FavoriteGames to count.
   * @example
   * // Count the number of FavoriteGames
   * const count = await prisma.favoriteGame.count({
   *   where: {
   *     // ... the filter for the FavoriteGames we want to count
   *   }
   * })
  **/
  count<T extends FavoriteGameCountArgs>(
    args?: Prisma.Subset<T, FavoriteGameCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FavoriteGameCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FavoriteGame.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FavoriteGameAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FavoriteGameAggregateArgs>(args: Prisma.Subset<T, FavoriteGameAggregateArgs>): Prisma.PrismaPromise<GetFavoriteGameAggregateType<T>>

  /**
   * Group by FavoriteGame.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FavoriteGameGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FavoriteGameGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FavoriteGameGroupByArgs['orderBy'] }
      : { orderBy?: FavoriteGameGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FavoriteGameGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFavoriteGameGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FavoriteGame model
 */
readonly fields: FavoriteGameFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FavoriteGame.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FavoriteGameClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FavoriteGame model
 */
export interface FavoriteGameFieldRefs {
  readonly id: Prisma.FieldRef<"FavoriteGame", 'String'>
  readonly userId: Prisma.FieldRef<"FavoriteGame", 'String'>
  readonly gameKey: Prisma.FieldRef<"FavoriteGame", 'String'>
  readonly createdAt: Prisma.FieldRef<"FavoriteGame", 'DateTime'>
}
    

// Custom InputTypes
/**
 * FavoriteGame findUnique
 */
export type FavoriteGameFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteGame
   */
  select?: Prisma.FavoriteGameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteGame
   */
  omit?: Prisma.FavoriteGameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteGameInclude<ExtArgs> | null
  /**
   * Filter, which FavoriteGame to fetch.
   */
  where: Prisma.FavoriteGameWhereUniqueInput
}

/**
 * FavoriteGame findUniqueOrThrow
 */
export type FavoriteGameFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteGame
   */
  select?: Prisma.FavoriteGameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteGame
   */
  omit?: Prisma.FavoriteGameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteGameInclude<ExtArgs> | null
  /**
   * Filter, which FavoriteGame to fetch.
   */
  where: Prisma.FavoriteGameWhereUniqueInput
}

/**
 * FavoriteGame findFirst
 */
export type FavoriteGameFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteGame
   */
  select?: Prisma.FavoriteGameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteGame
   */
  omit?: Prisma.FavoriteGameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteGameInclude<ExtArgs> | null
  /**
   * Filter, which FavoriteGame to fetch.
   */
  where?: Prisma.FavoriteGameWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FavoriteGames to fetch.
   */
  orderBy?: Prisma.FavoriteGameOrderByWithRelationInput | Prisma.FavoriteGameOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FavoriteGames.
   */
  cursor?: Prisma.FavoriteGameWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FavoriteGames from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FavoriteGames.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FavoriteGames.
   */
  distinct?: Prisma.FavoriteGameScalarFieldEnum | Prisma.FavoriteGameScalarFieldEnum[]
}

/**
 * FavoriteGame findFirstOrThrow
 */
export type FavoriteGameFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteGame
   */
  select?: Prisma.FavoriteGameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteGame
   */
  omit?: Prisma.FavoriteGameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteGameInclude<ExtArgs> | null
  /**
   * Filter, which FavoriteGame to fetch.
   */
  where?: Prisma.FavoriteGameWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FavoriteGames to fetch.
   */
  orderBy?: Prisma.FavoriteGameOrderByWithRelationInput | Prisma.FavoriteGameOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FavoriteGames.
   */
  cursor?: Prisma.FavoriteGameWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FavoriteGames from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FavoriteGames.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FavoriteGames.
   */
  distinct?: Prisma.FavoriteGameScalarFieldEnum | Prisma.FavoriteGameScalarFieldEnum[]
}

/**
 * FavoriteGame findMany
 */
export type FavoriteGameFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteGame
   */
  select?: Prisma.FavoriteGameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteGame
   */
  omit?: Prisma.FavoriteGameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteGameInclude<ExtArgs> | null
  /**
   * Filter, which FavoriteGames to fetch.
   */
  where?: Prisma.FavoriteGameWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FavoriteGames to fetch.
   */
  orderBy?: Prisma.FavoriteGameOrderByWithRelationInput | Prisma.FavoriteGameOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FavoriteGames.
   */
  cursor?: Prisma.FavoriteGameWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FavoriteGames from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FavoriteGames.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FavoriteGames.
   */
  distinct?: Prisma.FavoriteGameScalarFieldEnum | Prisma.FavoriteGameScalarFieldEnum[]
}

/**
 * FavoriteGame create
 */
export type FavoriteGameCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteGame
   */
  select?: Prisma.FavoriteGameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteGame
   */
  omit?: Prisma.FavoriteGameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteGameInclude<ExtArgs> | null
  /**
   * The data needed to create a FavoriteGame.
   */
  data: Prisma.XOR<Prisma.FavoriteGameCreateInput, Prisma.FavoriteGameUncheckedCreateInput>
}

/**
 * FavoriteGame createMany
 */
export type FavoriteGameCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FavoriteGames.
   */
  data: Prisma.FavoriteGameCreateManyInput | Prisma.FavoriteGameCreateManyInput[]
}

/**
 * FavoriteGame createManyAndReturn
 */
export type FavoriteGameCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteGame
   */
  select?: Prisma.FavoriteGameSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteGame
   */
  omit?: Prisma.FavoriteGameOmit<ExtArgs> | null
  /**
   * The data used to create many FavoriteGames.
   */
  data: Prisma.FavoriteGameCreateManyInput | Prisma.FavoriteGameCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteGameIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * FavoriteGame update
 */
export type FavoriteGameUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteGame
   */
  select?: Prisma.FavoriteGameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteGame
   */
  omit?: Prisma.FavoriteGameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteGameInclude<ExtArgs> | null
  /**
   * The data needed to update a FavoriteGame.
   */
  data: Prisma.XOR<Prisma.FavoriteGameUpdateInput, Prisma.FavoriteGameUncheckedUpdateInput>
  /**
   * Choose, which FavoriteGame to update.
   */
  where: Prisma.FavoriteGameWhereUniqueInput
}

/**
 * FavoriteGame updateMany
 */
export type FavoriteGameUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FavoriteGames.
   */
  data: Prisma.XOR<Prisma.FavoriteGameUpdateManyMutationInput, Prisma.FavoriteGameUncheckedUpdateManyInput>
  /**
   * Filter which FavoriteGames to update
   */
  where?: Prisma.FavoriteGameWhereInput
  /**
   * Limit how many FavoriteGames to update.
   */
  limit?: number
}

/**
 * FavoriteGame updateManyAndReturn
 */
export type FavoriteGameUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteGame
   */
  select?: Prisma.FavoriteGameSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteGame
   */
  omit?: Prisma.FavoriteGameOmit<ExtArgs> | null
  /**
   * The data used to update FavoriteGames.
   */
  data: Prisma.XOR<Prisma.FavoriteGameUpdateManyMutationInput, Prisma.FavoriteGameUncheckedUpdateManyInput>
  /**
   * Filter which FavoriteGames to update
   */
  where?: Prisma.FavoriteGameWhereInput
  /**
   * Limit how many FavoriteGames to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteGameIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * FavoriteGame upsert
 */
export type FavoriteGameUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteGame
   */
  select?: Prisma.FavoriteGameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteGame
   */
  omit?: Prisma.FavoriteGameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteGameInclude<ExtArgs> | null
  /**
   * The filter to search for the FavoriteGame to update in case it exists.
   */
  where: Prisma.FavoriteGameWhereUniqueInput
  /**
   * In case the FavoriteGame found by the `where` argument doesn't exist, create a new FavoriteGame with this data.
   */
  create: Prisma.XOR<Prisma.FavoriteGameCreateInput, Prisma.FavoriteGameUncheckedCreateInput>
  /**
   * In case the FavoriteGame was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FavoriteGameUpdateInput, Prisma.FavoriteGameUncheckedUpdateInput>
}

/**
 * FavoriteGame delete
 */
export type FavoriteGameDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteGame
   */
  select?: Prisma.FavoriteGameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteGame
   */
  omit?: Prisma.FavoriteGameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteGameInclude<ExtArgs> | null
  /**
   * Filter which FavoriteGame to delete.
   */
  where: Prisma.FavoriteGameWhereUniqueInput
}

/**
 * FavoriteGame deleteMany
 */
export type FavoriteGameDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FavoriteGames to delete
   */
  where?: Prisma.FavoriteGameWhereInput
  /**
   * Limit how many FavoriteGames to delete.
   */
  limit?: number
}

/**
 * FavoriteGame without action
 */
export type FavoriteGameDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteGame
   */
  select?: Prisma.FavoriteGameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteGame
   */
  omit?: Prisma.FavoriteGameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteGameInclude<ExtArgs> | null
}
