
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SetupPreset` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/wasm-compiler-edge"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SetupPreset
 * 
 */
export type SetupPresetModel = runtime.Types.Result.DefaultSelection<Prisma.$SetupPresetPayload>

export type AggregateSetupPreset = {
  _count: SetupPresetCountAggregateOutputType | null
  _min: SetupPresetMinAggregateOutputType | null
  _max: SetupPresetMaxAggregateOutputType | null
}

export type SetupPresetMinAggregateOutputType = {
  id: string | null
  userId: string | null
  gameKey: string | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SetupPresetMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  gameKey: string | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SetupPresetCountAggregateOutputType = {
  id: number
  userId: number
  gameKey: number
  name: number
  settings: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type SetupPresetMinAggregateInputType = {
  id?: true
  userId?: true
  gameKey?: true
  name?: true
  createdAt?: true
  updatedAt?: true
}

export type SetupPresetMaxAggregateInputType = {
  id?: true
  userId?: true
  gameKey?: true
  name?: true
  createdAt?: true
  updatedAt?: true
}

export type SetupPresetCountAggregateInputType = {
  id?: true
  userId?: true
  gameKey?: true
  name?: true
  settings?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type SetupPresetAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SetupPreset to aggregate.
   */
  where?: Prisma.SetupPresetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SetupPresets to fetch.
   */
  orderBy?: Prisma.SetupPresetOrderByWithRelationInput | Prisma.SetupPresetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SetupPresetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SetupPresets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SetupPresets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SetupPresets
  **/
  _count?: true | SetupPresetCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SetupPresetMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SetupPresetMaxAggregateInputType
}

export type GetSetupPresetAggregateType<T extends SetupPresetAggregateArgs> = {
      [P in keyof T & keyof AggregateSetupPreset]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSetupPreset[P]>
    : Prisma.GetScalarType<T[P], AggregateSetupPreset[P]>
}




export type SetupPresetGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SetupPresetWhereInput
  orderBy?: Prisma.SetupPresetOrderByWithAggregationInput | Prisma.SetupPresetOrderByWithAggregationInput[]
  by: Prisma.SetupPresetScalarFieldEnum[] | Prisma.SetupPresetScalarFieldEnum
  having?: Prisma.SetupPresetScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SetupPresetCountAggregateInputType | true
  _min?: SetupPresetMinAggregateInputType
  _max?: SetupPresetMaxAggregateInputType
}

export type SetupPresetGroupByOutputType = {
  id: string
  userId: string
  gameKey: string
  name: string
  settings: runtime.JsonValue
  createdAt: Date
  updatedAt: Date
  _count: SetupPresetCountAggregateOutputType | null
  _min: SetupPresetMinAggregateOutputType | null
  _max: SetupPresetMaxAggregateOutputType | null
}

export type GetSetupPresetGroupByPayload<T extends SetupPresetGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SetupPresetGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SetupPresetGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SetupPresetGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SetupPresetGroupByOutputType[P]>
      }
    >
  >



export type SetupPresetWhereInput = {
  AND?: Prisma.SetupPresetWhereInput | Prisma.SetupPresetWhereInput[]
  OR?: Prisma.SetupPresetWhereInput[]
  NOT?: Prisma.SetupPresetWhereInput | Prisma.SetupPresetWhereInput[]
  id?: Prisma.StringFilter<"SetupPreset"> | string
  userId?: Prisma.StringFilter<"SetupPreset"> | string
  gameKey?: Prisma.StringFilter<"SetupPreset"> | string
  name?: Prisma.StringFilter<"SetupPreset"> | string
  settings?: Prisma.JsonFilter<"SetupPreset">
  createdAt?: Prisma.DateTimeFilter<"SetupPreset"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SetupPreset"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type SetupPresetOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  gameKey?: Prisma.SortOrder
  name?: Prisma.SortOrder
  settings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type SetupPresetWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SetupPresetWhereInput | Prisma.SetupPresetWhereInput[]
  OR?: Prisma.SetupPresetWhereInput[]
  NOT?: Prisma.SetupPresetWhereInput | Prisma.SetupPresetWhereInput[]
  userId?: Prisma.StringFilter<"SetupPreset"> | string
  gameKey?: Prisma.StringFilter<"SetupPreset"> | string
  name?: Prisma.StringFilter<"SetupPreset"> | string
  settings?: Prisma.JsonFilter<"SetupPreset">
  createdAt?: Prisma.DateTimeFilter<"SetupPreset"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SetupPreset"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type SetupPresetOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  gameKey?: Prisma.SortOrder
  name?: Prisma.SortOrder
  settings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.SetupPresetCountOrderByAggregateInput
  _max?: Prisma.SetupPresetMaxOrderByAggregateInput
  _min?: Prisma.SetupPresetMinOrderByAggregateInput
}

export type SetupPresetScalarWhereWithAggregatesInput = {
  AND?: Prisma.SetupPresetScalarWhereWithAggregatesInput | Prisma.SetupPresetScalarWhereWithAggregatesInput[]
  OR?: Prisma.SetupPresetScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SetupPresetScalarWhereWithAggregatesInput | Prisma.SetupPresetScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SetupPreset"> | string
  userId?: Prisma.StringWithAggregatesFilter<"SetupPreset"> | string
  gameKey?: Prisma.StringWithAggregatesFilter<"SetupPreset"> | string
  name?: Prisma.StringWithAggregatesFilter<"SetupPreset"> | string
  settings?: Prisma.JsonWithAggregatesFilter<"SetupPreset">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SetupPreset"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"SetupPreset"> | Date | string
}

export type SetupPresetCreateInput = {
  id?: string
  gameKey: string
  name: string
  settings: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutSetupPresetsInput
}

export type SetupPresetUncheckedCreateInput = {
  id?: string
  userId: string
  gameKey: string
  name: string
  settings: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SetupPresetUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gameKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  settings?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutSetupPresetsNestedInput
}

export type SetupPresetUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  gameKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  settings?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SetupPresetCreateManyInput = {
  id?: string
  userId: string
  gameKey: string
  name: string
  settings: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SetupPresetUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gameKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  settings?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SetupPresetUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  gameKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  settings?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SetupPresetListRelationFilter = {
  every?: Prisma.SetupPresetWhereInput
  some?: Prisma.SetupPresetWhereInput
  none?: Prisma.SetupPresetWhereInput
}

export type SetupPresetOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SetupPresetCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  gameKey?: Prisma.SortOrder
  name?: Prisma.SortOrder
  settings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SetupPresetMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  gameKey?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SetupPresetMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  gameKey?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SetupPresetCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.SetupPresetCreateWithoutUserInput, Prisma.SetupPresetUncheckedCreateWithoutUserInput> | Prisma.SetupPresetCreateWithoutUserInput[] | Prisma.SetupPresetUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SetupPresetCreateOrConnectWithoutUserInput | Prisma.SetupPresetCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.SetupPresetCreateManyUserInputEnvelope
  connect?: Prisma.SetupPresetWhereUniqueInput | Prisma.SetupPresetWhereUniqueInput[]
}

export type SetupPresetUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.SetupPresetCreateWithoutUserInput, Prisma.SetupPresetUncheckedCreateWithoutUserInput> | Prisma.SetupPresetCreateWithoutUserInput[] | Prisma.SetupPresetUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SetupPresetCreateOrConnectWithoutUserInput | Prisma.SetupPresetCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.SetupPresetCreateManyUserInputEnvelope
  connect?: Prisma.SetupPresetWhereUniqueInput | Prisma.SetupPresetWhereUniqueInput[]
}

export type SetupPresetUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.SetupPresetCreateWithoutUserInput, Prisma.SetupPresetUncheckedCreateWithoutUserInput> | Prisma.SetupPresetCreateWithoutUserInput[] | Prisma.SetupPresetUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SetupPresetCreateOrConnectWithoutUserInput | Prisma.SetupPresetCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.SetupPresetUpsertWithWhereUniqueWithoutUserInput | Prisma.SetupPresetUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.SetupPresetCreateManyUserInputEnvelope
  set?: Prisma.SetupPresetWhereUniqueInput | Prisma.SetupPresetWhereUniqueInput[]
  disconnect?: Prisma.SetupPresetWhereUniqueInput | Prisma.SetupPresetWhereUniqueInput[]
  delete?: Prisma.SetupPresetWhereUniqueInput | Prisma.SetupPresetWhereUniqueInput[]
  connect?: Prisma.SetupPresetWhereUniqueInput | Prisma.SetupPresetWhereUniqueInput[]
  update?: Prisma.SetupPresetUpdateWithWhereUniqueWithoutUserInput | Prisma.SetupPresetUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.SetupPresetUpdateManyWithWhereWithoutUserInput | Prisma.SetupPresetUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.SetupPresetScalarWhereInput | Prisma.SetupPresetScalarWhereInput[]
}

export type SetupPresetUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.SetupPresetCreateWithoutUserInput, Prisma.SetupPresetUncheckedCreateWithoutUserInput> | Prisma.SetupPresetCreateWithoutUserInput[] | Prisma.SetupPresetUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SetupPresetCreateOrConnectWithoutUserInput | Prisma.SetupPresetCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.SetupPresetUpsertWithWhereUniqueWithoutUserInput | Prisma.SetupPresetUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.SetupPresetCreateManyUserInputEnvelope
  set?: Prisma.SetupPresetWhereUniqueInput | Prisma.SetupPresetWhereUniqueInput[]
  disconnect?: Prisma.SetupPresetWhereUniqueInput | Prisma.SetupPresetWhereUniqueInput[]
  delete?: Prisma.SetupPresetWhereUniqueInput | Prisma.SetupPresetWhereUniqueInput[]
  connect?: Prisma.SetupPresetWhereUniqueInput | Prisma.SetupPresetWhereUniqueInput[]
  update?: Prisma.SetupPresetUpdateWithWhereUniqueWithoutUserInput | Prisma.SetupPresetUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.SetupPresetUpdateManyWithWhereWithoutUserInput | Prisma.SetupPresetUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.SetupPresetScalarWhereInput | Prisma.SetupPresetScalarWhereInput[]
}

export type SetupPresetCreateWithoutUserInput = {
  id?: string
  gameKey: string
  name: string
  settings: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SetupPresetUncheckedCreateWithoutUserInput = {
  id?: string
  gameKey: string
  name: string
  settings: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SetupPresetCreateOrConnectWithoutUserInput = {
  where: Prisma.SetupPresetWhereUniqueInput
  create: Prisma.XOR<Prisma.SetupPresetCreateWithoutUserInput, Prisma.SetupPresetUncheckedCreateWithoutUserInput>
}

export type SetupPresetCreateManyUserInputEnvelope = {
  data: Prisma.SetupPresetCreateManyUserInput | Prisma.SetupPresetCreateManyUserInput[]
}

export type SetupPresetUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.SetupPresetWhereUniqueInput
  update: Prisma.XOR<Prisma.SetupPresetUpdateWithoutUserInput, Prisma.SetupPresetUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.SetupPresetCreateWithoutUserInput, Prisma.SetupPresetUncheckedCreateWithoutUserInput>
}

export type SetupPresetUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.SetupPresetWhereUniqueInput
  data: Prisma.XOR<Prisma.SetupPresetUpdateWithoutUserInput, Prisma.SetupPresetUncheckedUpdateWithoutUserInput>
}

export type SetupPresetUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.SetupPresetScalarWhereInput
  data: Prisma.XOR<Prisma.SetupPresetUpdateManyMutationInput, Prisma.SetupPresetUncheckedUpdateManyWithoutUserInput>
}

export type SetupPresetScalarWhereInput = {
  AND?: Prisma.SetupPresetScalarWhereInput | Prisma.SetupPresetScalarWhereInput[]
  OR?: Prisma.SetupPresetScalarWhereInput[]
  NOT?: Prisma.SetupPresetScalarWhereInput | Prisma.SetupPresetScalarWhereInput[]
  id?: Prisma.StringFilter<"SetupPreset"> | string
  userId?: Prisma.StringFilter<"SetupPreset"> | string
  gameKey?: Prisma.StringFilter<"SetupPreset"> | string
  name?: Prisma.StringFilter<"SetupPreset"> | string
  settings?: Prisma.JsonFilter<"SetupPreset">
  createdAt?: Prisma.DateTimeFilter<"SetupPreset"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SetupPreset"> | Date | string
}

export type SetupPresetCreateManyUserInput = {
  id?: string
  gameKey: string
  name: string
  settings: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SetupPresetUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gameKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  settings?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SetupPresetUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gameKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  settings?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SetupPresetUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gameKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  settings?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type SetupPresetSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  gameKey?: boolean
  name?: boolean
  settings?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["setupPreset"]>

export type SetupPresetSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  gameKey?: boolean
  name?: boolean
  settings?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["setupPreset"]>

export type SetupPresetSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  gameKey?: boolean
  name?: boolean
  settings?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["setupPreset"]>

export type SetupPresetSelectScalar = {
  id?: boolean
  userId?: boolean
  gameKey?: boolean
  name?: boolean
  settings?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type SetupPresetOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "gameKey" | "name" | "settings" | "createdAt" | "updatedAt", ExtArgs["result"]["setupPreset"]>
export type SetupPresetInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type SetupPresetIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type SetupPresetIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $SetupPresetPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SetupPreset"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    gameKey: string
    name: string
    settings: runtime.JsonValue
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["setupPreset"]>
  composites: {}
}

export type SetupPresetGetPayload<S extends boolean | null | undefined | SetupPresetDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SetupPresetPayload, S>

export type SetupPresetCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SetupPresetFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SetupPresetCountAggregateInputType | true
  }

export interface SetupPresetDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SetupPreset'], meta: { name: 'SetupPreset' } }
  /**
   * Find zero or one SetupPreset that matches the filter.
   * @param {SetupPresetFindUniqueArgs} args - Arguments to find a SetupPreset
   * @example
   * // Get one SetupPreset
   * const setupPreset = await prisma.setupPreset.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SetupPresetFindUniqueArgs>(args: Prisma.SelectSubset<T, SetupPresetFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SetupPresetClient<runtime.Types.Result.GetResult<Prisma.$SetupPresetPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SetupPreset that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SetupPresetFindUniqueOrThrowArgs} args - Arguments to find a SetupPreset
   * @example
   * // Get one SetupPreset
   * const setupPreset = await prisma.setupPreset.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SetupPresetFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SetupPresetFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SetupPresetClient<runtime.Types.Result.GetResult<Prisma.$SetupPresetPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SetupPreset that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetupPresetFindFirstArgs} args - Arguments to find a SetupPreset
   * @example
   * // Get one SetupPreset
   * const setupPreset = await prisma.setupPreset.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SetupPresetFindFirstArgs>(args?: Prisma.SelectSubset<T, SetupPresetFindFirstArgs<ExtArgs>>): Prisma.Prisma__SetupPresetClient<runtime.Types.Result.GetResult<Prisma.$SetupPresetPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SetupPreset that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetupPresetFindFirstOrThrowArgs} args - Arguments to find a SetupPreset
   * @example
   * // Get one SetupPreset
   * const setupPreset = await prisma.setupPreset.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SetupPresetFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SetupPresetFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SetupPresetClient<runtime.Types.Result.GetResult<Prisma.$SetupPresetPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SetupPresets that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetupPresetFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SetupPresets
   * const setupPresets = await prisma.setupPreset.findMany()
   * 
   * // Get first 10 SetupPresets
   * const setupPresets = await prisma.setupPreset.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const setupPresetWithIdOnly = await prisma.setupPreset.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SetupPresetFindManyArgs>(args?: Prisma.SelectSubset<T, SetupPresetFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SetupPresetPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SetupPreset.
   * @param {SetupPresetCreateArgs} args - Arguments to create a SetupPreset.
   * @example
   * // Create one SetupPreset
   * const SetupPreset = await prisma.setupPreset.create({
   *   data: {
   *     // ... data to create a SetupPreset
   *   }
   * })
   * 
   */
  create<T extends SetupPresetCreateArgs>(args: Prisma.SelectSubset<T, SetupPresetCreateArgs<ExtArgs>>): Prisma.Prisma__SetupPresetClient<runtime.Types.Result.GetResult<Prisma.$SetupPresetPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SetupPresets.
   * @param {SetupPresetCreateManyArgs} args - Arguments to create many SetupPresets.
   * @example
   * // Create many SetupPresets
   * const setupPreset = await prisma.setupPreset.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SetupPresetCreateManyArgs>(args?: Prisma.SelectSubset<T, SetupPresetCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SetupPresets and returns the data saved in the database.
   * @param {SetupPresetCreateManyAndReturnArgs} args - Arguments to create many SetupPresets.
   * @example
   * // Create many SetupPresets
   * const setupPreset = await prisma.setupPreset.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SetupPresets and only return the `id`
   * const setupPresetWithIdOnly = await prisma.setupPreset.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SetupPresetCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SetupPresetCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SetupPresetPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SetupPreset.
   * @param {SetupPresetDeleteArgs} args - Arguments to delete one SetupPreset.
   * @example
   * // Delete one SetupPreset
   * const SetupPreset = await prisma.setupPreset.delete({
   *   where: {
   *     // ... filter to delete one SetupPreset
   *   }
   * })
   * 
   */
  delete<T extends SetupPresetDeleteArgs>(args: Prisma.SelectSubset<T, SetupPresetDeleteArgs<ExtArgs>>): Prisma.Prisma__SetupPresetClient<runtime.Types.Result.GetResult<Prisma.$SetupPresetPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SetupPreset.
   * @param {SetupPresetUpdateArgs} args - Arguments to update one SetupPreset.
   * @example
   * // Update one SetupPreset
   * const setupPreset = await prisma.setupPreset.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SetupPresetUpdateArgs>(args: Prisma.SelectSubset<T, SetupPresetUpdateArgs<ExtArgs>>): Prisma.Prisma__SetupPresetClient<runtime.Types.Result.GetResult<Prisma.$SetupPresetPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SetupPresets.
   * @param {SetupPresetDeleteManyArgs} args - Arguments to filter SetupPresets to delete.
   * @example
   * // Delete a few SetupPresets
   * const { count } = await prisma.setupPreset.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SetupPresetDeleteManyArgs>(args?: Prisma.SelectSubset<T, SetupPresetDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SetupPresets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetupPresetUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SetupPresets
   * const setupPreset = await prisma.setupPreset.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SetupPresetUpdateManyArgs>(args: Prisma.SelectSubset<T, SetupPresetUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SetupPresets and returns the data updated in the database.
   * @param {SetupPresetUpdateManyAndReturnArgs} args - Arguments to update many SetupPresets.
   * @example
   * // Update many SetupPresets
   * const setupPreset = await prisma.setupPreset.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SetupPresets and only return the `id`
   * const setupPresetWithIdOnly = await prisma.setupPreset.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SetupPresetUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SetupPresetUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SetupPresetPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SetupPreset.
   * @param {SetupPresetUpsertArgs} args - Arguments to update or create a SetupPreset.
   * @example
   * // Update or create a SetupPreset
   * const setupPreset = await prisma.setupPreset.upsert({
   *   create: {
   *     // ... data to create a SetupPreset
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SetupPreset we want to update
   *   }
   * })
   */
  upsert<T extends SetupPresetUpsertArgs>(args: Prisma.SelectSubset<T, SetupPresetUpsertArgs<ExtArgs>>): Prisma.Prisma__SetupPresetClient<runtime.Types.Result.GetResult<Prisma.$SetupPresetPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SetupPresets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetupPresetCountArgs} args - Arguments to filter SetupPresets to count.
   * @example
   * // Count the number of SetupPresets
   * const count = await prisma.setupPreset.count({
   *   where: {
   *     // ... the filter for the SetupPresets we want to count
   *   }
   * })
  **/
  count<T extends SetupPresetCountArgs>(
    args?: Prisma.Subset<T, SetupPresetCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SetupPresetCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SetupPreset.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetupPresetAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SetupPresetAggregateArgs>(args: Prisma.Subset<T, SetupPresetAggregateArgs>): Prisma.PrismaPromise<GetSetupPresetAggregateType<T>>

  /**
   * Group by SetupPreset.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetupPresetGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SetupPresetGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SetupPresetGroupByArgs['orderBy'] }
      : { orderBy?: SetupPresetGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SetupPresetGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSetupPresetGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SetupPreset model
 */
readonly fields: SetupPresetFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SetupPreset.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SetupPresetClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SetupPreset model
 */
export interface SetupPresetFieldRefs {
  readonly id: Prisma.FieldRef<"SetupPreset", 'String'>
  readonly userId: Prisma.FieldRef<"SetupPreset", 'String'>
  readonly gameKey: Prisma.FieldRef<"SetupPreset", 'String'>
  readonly name: Prisma.FieldRef<"SetupPreset", 'String'>
  readonly settings: Prisma.FieldRef<"SetupPreset", 'Json'>
  readonly createdAt: Prisma.FieldRef<"SetupPreset", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"SetupPreset", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SetupPreset findUnique
 */
export type SetupPresetFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetupPreset
   */
  select?: Prisma.SetupPresetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetupPreset
   */
  omit?: Prisma.SetupPresetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetupPresetInclude<ExtArgs> | null
  /**
   * Filter, which SetupPreset to fetch.
   */
  where: Prisma.SetupPresetWhereUniqueInput
}

/**
 * SetupPreset findUniqueOrThrow
 */
export type SetupPresetFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetupPreset
   */
  select?: Prisma.SetupPresetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetupPreset
   */
  omit?: Prisma.SetupPresetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetupPresetInclude<ExtArgs> | null
  /**
   * Filter, which SetupPreset to fetch.
   */
  where: Prisma.SetupPresetWhereUniqueInput
}

/**
 * SetupPreset findFirst
 */
export type SetupPresetFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetupPreset
   */
  select?: Prisma.SetupPresetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetupPreset
   */
  omit?: Prisma.SetupPresetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetupPresetInclude<ExtArgs> | null
  /**
   * Filter, which SetupPreset to fetch.
   */
  where?: Prisma.SetupPresetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SetupPresets to fetch.
   */
  orderBy?: Prisma.SetupPresetOrderByWithRelationInput | Prisma.SetupPresetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SetupPresets.
   */
  cursor?: Prisma.SetupPresetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SetupPresets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SetupPresets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SetupPresets.
   */
  distinct?: Prisma.SetupPresetScalarFieldEnum | Prisma.SetupPresetScalarFieldEnum[]
}

/**
 * SetupPreset findFirstOrThrow
 */
export type SetupPresetFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetupPreset
   */
  select?: Prisma.SetupPresetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetupPreset
   */
  omit?: Prisma.SetupPresetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetupPresetInclude<ExtArgs> | null
  /**
   * Filter, which SetupPreset to fetch.
   */
  where?: Prisma.SetupPresetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SetupPresets to fetch.
   */
  orderBy?: Prisma.SetupPresetOrderByWithRelationInput | Prisma.SetupPresetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SetupPresets.
   */
  cursor?: Prisma.SetupPresetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SetupPresets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SetupPresets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SetupPresets.
   */
  distinct?: Prisma.SetupPresetScalarFieldEnum | Prisma.SetupPresetScalarFieldEnum[]
}

/**
 * SetupPreset findMany
 */
export type SetupPresetFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetupPreset
   */
  select?: Prisma.SetupPresetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetupPreset
   */
  omit?: Prisma.SetupPresetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetupPresetInclude<ExtArgs> | null
  /**
   * Filter, which SetupPresets to fetch.
   */
  where?: Prisma.SetupPresetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SetupPresets to fetch.
   */
  orderBy?: Prisma.SetupPresetOrderByWithRelationInput | Prisma.SetupPresetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SetupPresets.
   */
  cursor?: Prisma.SetupPresetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SetupPresets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SetupPresets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SetupPresets.
   */
  distinct?: Prisma.SetupPresetScalarFieldEnum | Prisma.SetupPresetScalarFieldEnum[]
}

/**
 * SetupPreset create
 */
export type SetupPresetCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetupPreset
   */
  select?: Prisma.SetupPresetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetupPreset
   */
  omit?: Prisma.SetupPresetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetupPresetInclude<ExtArgs> | null
  /**
   * The data needed to create a SetupPreset.
   */
  data: Prisma.XOR<Prisma.SetupPresetCreateInput, Prisma.SetupPresetUncheckedCreateInput>
}

/**
 * SetupPreset createMany
 */
export type SetupPresetCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SetupPresets.
   */
  data: Prisma.SetupPresetCreateManyInput | Prisma.SetupPresetCreateManyInput[]
}

/**
 * SetupPreset createManyAndReturn
 */
export type SetupPresetCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetupPreset
   */
  select?: Prisma.SetupPresetSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SetupPreset
   */
  omit?: Prisma.SetupPresetOmit<ExtArgs> | null
  /**
   * The data used to create many SetupPresets.
   */
  data: Prisma.SetupPresetCreateManyInput | Prisma.SetupPresetCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetupPresetIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SetupPreset update
 */
export type SetupPresetUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetupPreset
   */
  select?: Prisma.SetupPresetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetupPreset
   */
  omit?: Prisma.SetupPresetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetupPresetInclude<ExtArgs> | null
  /**
   * The data needed to update a SetupPreset.
   */
  data: Prisma.XOR<Prisma.SetupPresetUpdateInput, Prisma.SetupPresetUncheckedUpdateInput>
  /**
   * Choose, which SetupPreset to update.
   */
  where: Prisma.SetupPresetWhereUniqueInput
}

/**
 * SetupPreset updateMany
 */
export type SetupPresetUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SetupPresets.
   */
  data: Prisma.XOR<Prisma.SetupPresetUpdateManyMutationInput, Prisma.SetupPresetUncheckedUpdateManyInput>
  /**
   * Filter which SetupPresets to update
   */
  where?: Prisma.SetupPresetWhereInput
  /**
   * Limit how many SetupPresets to update.
   */
  limit?: number
}

/**
 * SetupPreset updateManyAndReturn
 */
export type SetupPresetUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetupPreset
   */
  select?: Prisma.SetupPresetSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SetupPreset
   */
  omit?: Prisma.SetupPresetOmit<ExtArgs> | null
  /**
   * The data used to update SetupPresets.
   */
  data: Prisma.XOR<Prisma.SetupPresetUpdateManyMutationInput, Prisma.SetupPresetUncheckedUpdateManyInput>
  /**
   * Filter which SetupPresets to update
   */
  where?: Prisma.SetupPresetWhereInput
  /**
   * Limit how many SetupPresets to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetupPresetIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SetupPreset upsert
 */
export type SetupPresetUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetupPreset
   */
  select?: Prisma.SetupPresetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetupPreset
   */
  omit?: Prisma.SetupPresetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetupPresetInclude<ExtArgs> | null
  /**
   * The filter to search for the SetupPreset to update in case it exists.
   */
  where: Prisma.SetupPresetWhereUniqueInput
  /**
   * In case the SetupPreset found by the `where` argument doesn't exist, create a new SetupPreset with this data.
   */
  create: Prisma.XOR<Prisma.SetupPresetCreateInput, Prisma.SetupPresetUncheckedCreateInput>
  /**
   * In case the SetupPreset was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SetupPresetUpdateInput, Prisma.SetupPresetUncheckedUpdateInput>
}

/**
 * SetupPreset delete
 */
export type SetupPresetDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetupPreset
   */
  select?: Prisma.SetupPresetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetupPreset
   */
  omit?: Prisma.SetupPresetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetupPresetInclude<ExtArgs> | null
  /**
   * Filter which SetupPreset to delete.
   */
  where: Prisma.SetupPresetWhereUniqueInput
}

/**
 * SetupPreset deleteMany
 */
export type SetupPresetDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SetupPresets to delete
   */
  where?: Prisma.SetupPresetWhereInput
  /**
   * Limit how many SetupPresets to delete.
   */
  limit?: number
}

/**
 * SetupPreset without action
 */
export type SetupPresetDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetupPreset
   */
  select?: Prisma.SetupPresetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetupPreset
   */
  omit?: Prisma.SetupPresetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetupPresetInclude<ExtArgs> | null
}
